services:
  - type: web
    name: supplements-server
    runtime: node
    plan: free
    region: frankfurt
    repo: https://github.com/artem-yaremchuk/supplements-app
    rootDir: server
    buildCommand: |
      rm -rf dist
      npm install
      npx prisma generate
      npm run build
      echo "===== DIST CONTENT ====="
      ls -R dist
      npx prisma migrate deploy
    startCommand: npm run start:prod
    autoDeployTrigger: checksPass
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22 
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
